import type { Industry, IndustryImage } from "@/types/content";

/**
 * Industries Smart Channels serves — the sixteen approved by the client.
 *
 * Each `note` describes the *nature of the delivery environment*, not a
 * completed engagement. "Temporary networks stood up on tight timelines" is a
 * statement about what the sector demands; it is not a claim that a specific
 * project was delivered there. That distinction is deliberate — no project,
 * client or track record is implied anywhere in this file.
 *
 * ---------------------------------------------------------------------------
 * IMAGERY — photography is the intended primary source
 * ---------------------------------------------------------------------------
 * Each entry supports two images:
 *
 *   photo  — a real photograph of the environment. This is what the section is
 *            designed around and what should ship. Rendered whenever present.
 *   art    — a brand-generated abstract panel, used ONLY while `photo` is
 *            absent. It is a stopgap so the section is presentable before
 *            photography lands; it is not the intended final design.
 *
 * No industry photography has been supplied, so every entry currently falls
 * back to `art`. `industryPhotoReadiness()` reports the gap, the development
 * build labels each fallback panel, and the production checklist in
 * FINAL_PROJECT_REPORT.md treats this as an open item.
 *
 * TO ADD A PHOTOGRAPH
 *   1. Save it as `source-assets/industries/<id>.jpg` — the id below, exactly.
 *   2. Run `npm run assets:photos`. It produces an optimised WebP plus a blur
 *      placeholder and prints the `photo: { … }` block to paste in.
 *   3. Paste that block into the entry. Nothing else changes.
 *
 * `shotBrief` on each entry is the commissioning specification for that
 * photograph — hand it to a photographer or use it as stock search criteria.
 *
 * IMAGE REQUIREMENTS
 *   - 16:10 landscape, minimum 1600×1000, ideally 2400×1500
 *   - Composed with the lower third relatively clear: the industry title and
 *     note sit there over a scrim
 *   - Real environments, not obvious stock clichés (no handshakes, no
 *     lens-flare server rooms, no people pointing at screens)
 *   - Licensed for commercial web use, or owned outright
 */

/** Fallback art path for an industry, generated by scripts/generate-industry-art.mjs. */
function art(id: string): IndustryImage {
  return { src: `/images/industries/${id}.svg`, width: 1600, height: 1000 };
}

export const industries: readonly Industry[] = [
  {
    id: "sporting-events",
    title: { en: "Major Sporting Events", ar: "الفعاليات الرياضية الكبرى" },
    note: {
      en: "Temporary networks stood up on fixed timelines, with no second chance on event day.",
      ar: "شبكات مؤقتة تُنشأ ضمن جداول محددة، دون فرصة ثانية في يوم الحدث.",
    },
    art: art("sporting-events"),
    shotBrief:
      "Large event venue during an event — crowd and floodlights visible, wide angle. Avoid identifiable athletes or branded team kit.",
  },
  {
    id: "stadiums",
    title: { en: "Stadiums & Sports Cities", ar: "الملاعب والمدن الرياضية" },
    note: {
      en: "High-density connectivity and security systems across large venues.",
      ar: "اتصال عالي الكثافة وأنظمة أمن تغطّي منشآت واسعة.",
    },
    art: art("stadiums"),
    shotBrief:
      "Modern stadium exterior or empty bowl interior, ideally at dusk. Architectural emphasis rather than crowd.",
  },
  {
    id: "motorsport",
    title: { en: "Motorsport & Racing", ar: "رياضة المحركات والسباقات" },
    note: {
      en: "Trackside infrastructure where latency and reliability are measured in milliseconds.",
      ar: "بنية تحتية بجوار المضمار تُقاس فيها الاستجابة والاعتمادية بأجزاء من الثانية.",
    },
    art: art("motorsport"),
    shotBrief:
      "Circuit trackside — pit lane, timing gantry or grandstand. Avoid identifiable team liveries and sponsor logos.",
  },
  {
    id: "cultural-seasons",
    title: { en: "Cultural Seasons & Festivals", ar: "المواسم الثقافية والمهرجانات" },
    note: {
      en: "Audio, video and network systems for open sites and seasonal venues.",
      ar: "أنظمة صوت وفيديو وشبكات للمواقع المفتوحة والمنشآت الموسمية.",
    },
    art: art("cultural-seasons"),
    shotBrief:
      "Outdoor festival site at night — stage lighting, temporary structures, LED screens. Saudi cultural season imagery preferred.",
  },
  {
    id: "government",
    title: { en: "Government & Public Sector", ar: "القطاع الحكومي والعام" },
    note: {
      en: "Systems built to meet public-sector security and procurement requirements.",
      ar: "أنظمة مبنية وفق متطلبات الأمن والشراء في القطاع الحكومي.",
    },
    art: art("government"),
    shotBrief:
      "Formal institutional architecture — a ministry or civic building exterior. Restrained, authoritative. No national insignia.",
  },
  {
    id: "holy-sites",
    title: { en: "Religious & Holy Sites", ar: "المواقع الدينية والمشاعر المقدسة" },
    note: {
      en: "Environments with extreme peak loads and an absolute requirement for continuity.",
      ar: "بيئات ذات أحمال ذروة استثنائية ومتطلب مطلق لاستمرارية الخدمة.",
    },
    art: art("holy-sites"),
    shotBrief:
      "Architectural or infrastructure view of a holy-site precinct. Must be handled respectfully — prefer architecture, wayfinding or crowd-management infrastructure over worshippers. Confirm the image is appropriate before publishing.",
  },
  {
    id: "giga-projects",
    title: { en: "Giga Projects", ar: "المشاريع العملاقة" },
    note: {
      en: "Long-horizon developments requiring infrastructure that scales in phases.",
      ar: "مشاريع تنموية طويلة المدى تتطلّب بنية تحتية قابلة للتوسّع على مراحل.",
    },
    art: art("giga-projects"),
    shotBrief:
      "Large-scale development under construction — cranes, groundworks, masterplan scale. Aerial or elevated viewpoint.",
  },
  {
    id: "hospitality",
    title: { en: "Hospitality & F&B", ar: "الضيافة والأغذية والمشروبات" },
    note: {
      en: "Guest connectivity, point-of-sale and back-of-house systems on one network.",
      ar: "اتصال الضيوف وأنظمة نقاط البيع والعمليات الخلفية على شبكة واحدة.",
    },
    art: art("hospitality"),
    shotBrief:
      "Hotel lobby or upscale restaurant interior, warm evening light. Architecture and fit-out rather than diners.",
  },
  {
    id: "healthcare",
    title: { en: "Healthcare", ar: "الرعاية الصحية" },
    note: {
      en: "Clinical environments where network availability is a patient-safety matter.",
      ar: "بيئات سريرية يمثّل فيها توافر الشبكة مسألة تتعلّق بسلامة المرضى.",
    },
    art: art("healthcare"),
    shotBrief:
      "Modern hospital corridor, imaging suite or nurses' station. No patients, no identifiable staff faces.",
  },
  {
    id: "education",
    title: { en: "Education", ar: "التعليم" },
    note: {
      en: "Campus-wide coverage, segmented access and classroom AV.",
      ar: "تغطية شاملة للحرم التعليمي، ووصول مُقسَّم، وأنظمة صوت وصورة للقاعات.",
    },
    art: art("education"),
    shotBrief:
      "University campus exterior or a modern lecture theatre with AV installed. Avoid identifiable students.",
  },
  {
    id: "banking",
    title: { en: "Banking & Finance", ar: "البنوك والتمويل" },
    note: {
      en: "Regulated environments with strict controls over access and data.",
      ar: "بيئات خاضعة للتنظيم بضوابط صارمة على الوصول والبيانات.",
    },
    art: art("banking"),
    shotBrief:
      "Corporate banking tower exterior or a formal trading/operations floor. No visible bank branding.",
  },
  {
    id: "industrial",
    title: { en: "Industrial & Energy", ar: "الصناعة والطاقة" },
    note: {
      en: "Harsh-environment installations and infrastructure that tolerates them.",
      ar: "تركيبات في بيئات قاسية وبنية تحتية قادرة على تحمّلها.",
    },
    art: art("industrial"),
    shotBrief:
      "Petrochemical plant, refinery or heavy industrial facility. Wide angle, ideally dusk or dawn.",
  },
  {
    id: "transport",
    title: { en: "Transport & Rail", ar: "النقل والسكك الحديدية" },
    note: {
      en: "Distributed sites linked into one managed, monitored network.",
      ar: "مواقع موزّعة مرتبطة ضمن شبكة واحدة مُدارة ومراقَبة.",
    },
    art: art("transport"),
    shotBrief:
      "Modern rail station concourse, platform or metro interior. Architecture and systems over passengers.",
  },
  {
    id: "diplomatic",
    title: { en: "Diplomatic Missions", ar: "البعثات الدبلوماسية" },
    note: {
      en: "Facilities where confidentiality and physical security requirements are elevated.",
      ar: "منشآت ترتفع فيها متطلبات السرية والأمن المادي.",
    },
    art: art("diplomatic"),
    shotBrief:
      "Formal diplomatic-quarter architecture or a secure entrance/perimeter. No identifiable flags or national emblems.",
  },
  {
    id: "retail",
    title: { en: "Retail & Malls", ar: "التجزئة والمراكز التجارية" },
    note: {
      en: "Multi-tenant connectivity, surveillance and point-of-sale infrastructure.",
      ar: "بنية اتصال ومراقبة ونقاط بيع لمواقع متعددة المستأجرين.",
    },
    art: art("retail"),
    shotBrief:
      "Modern shopping-mall atrium, wide interior. Avoid recognisable retailer branding.",
  },
  {
    id: "media",
    title: { en: "Media & Broadcast", ar: "الإعلام والبث" },
    note: {
      en: "High-bandwidth audio and video paths with tight timing requirements.",
      ar: "مسارات صوت وفيديو عالية النطاق بمتطلبات توقيت دقيقة.",
    },
    art: art("media"),
    shotBrief:
      "Broadcast gallery, control room or outside-broadcast truck interior — monitor walls and mixing desks.",
  },
];

/**
 * How many industries have real photography.
 *
 * The section is designed around photographs; the generated panels are a
 * stopgap. This is surfaced in the development build and in the launch
 * checklist so "still on fallback art" cannot quietly become permanent.
 */
export function industryPhotoReadiness(): {
  total: number;
  withPhoto: number;
  missing: readonly string[];
} {
  const missing = industries.filter((i) => !i.photo).map((i) => i.id);
  return {
    total: industries.length,
    withPhoto: industries.length - missing.length,
    missing,
  };
}
